name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.0
        check-latest: true

    - name: Init mods
      run: go mod download && go mod verify

    - name: Build
      run:  cd ./sensor && go build -v ./...

    - name: UnitTests
      run: go test -cover -v ./...
