name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Init mods
      run: go mod download && go mod verify

    - name: Build
      run:  cd ./sensor && go build -v ./...

    - name: TestSensor
      run: cd ./libsensor && go test -cover -v ./...

    - name: TestSettings
      run: cd ./libsettings && go test -cover -v ./...

    - name: TestSysCmd
      run: cd ./syscmd && go test -cover -v ./...

    - name: TestHandlers
      run: cd ./webservice/handlers && go test -cover -v ./...
